blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://axonium.fr/help
    about: Check the documentation before opening an issue
  - name: ðŸ“§ Contact
    url: https://axonium.fr/support
    about: For private or urgent requests
